version: "3.8"
services:
  portainer:
    image: portainer/portainer-ee:2.10.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.service: "portainer"
      traefik.http.routers.portainer.entrypoints: "websecure"
      traefik.http.routers.traefik.tls.certresolver: "letsencrypt"
      traefik.http.routers.portainer.rule: "Host(`portainer.devantler.com`)"
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

  portainer-agent:
    image: portainer/agent:2.11.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global

networks:
  agent_network:
    external: true

volumes:
  portainer_data: null