version: "3.8"
services:
  portainer:
    image: portainer/portainer-ee:linux-arm-2.10.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - public
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      labels:
        traefik.enable: "true"
        traefik.http.routers.portainer.rule: "Host(`portainer.devantler.com`)"
        traefik.http.routers.portainer.entrypoints: "websecure"
        traefik.http.routers.portainer.tls.certresolver: "letsencrypt"
        traefik.http.services.portainer.loadbalancer.server.port: 9000
        traefik.http.routers.portainer.service: "portainer"

  agent:
    image: portainer/agent:linux-arm-2.11.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  public:
    external: true
  agent_network:
    external: true

volumes:
  portainer_data:
