version: "3.8"
services:
  pihole:
    hostname: pihole.devantler.com
    image: pihole/pihole:2021.11
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Copenhagen'
      WEBPASSWORD_FILE: '/run/secrets/pihole_password'
    secrets:
    - pihole_password
    volumes:
      - 'etc-pihole:/etc/pihole'
      - 'etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN

secrets:
  pihole_password:
    external: true

volumes:
  etc-pihole:
    driver: local
  etc-dnsmasq.d:
    driver: local