version: "3.8"

services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge:1.0.5
    user: root
    volumes:
      - var_opt_mssql:/var/opt/mssql
      - var_opt_mssql-extensibility:/var/opt/mssql-extensibility
      - var_opt_mssql-extensibility_data:/var/opt/mssql-extensibility/data
      - var_opt_mssql-extensibility_log:/var/opt/mssql-extensibility/log
    networks:
      - internal
    environment:
      MSSQL_SA_PASSWORD: ${PASSWORD:?}
      ACCEPT_EULA: 1

volumes:
  var_opt_mssql:
  var_opt_mssql-extensibility:
  var_opt_mssql-extensibility_data:
  var_opt_mssqlextensibility_log:
  
networks:
  internal:
    external: true
