version: "3.8"

services:
  plantuml:
    image: plantuml/plantuml-server:v1.2022.2
    networks:
      - public
      - auth
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.plantuml.rule: "Host(`plantuml.${DOMAIN:?}`)"
        traefik.http.routers.plantuml.entrypoints: "websecure"
        traefik.http.routers.plantuml.tls.certresolver: "letsencrypt"
        traefik.http.services.plantuml.loadbalancer.server.port: 8080
        traefik.http.routers.plantuml.service: "plantuml"
        traefik.http.routers.plantuml.middlewares: plantuml-auth
        traefik.http.middlewares.plantuml-auth.basicauth.users: ${ADMIN_USER:?}:${HASHED_PASSWORD:?},${GUEST_USER:?}:${GUEST_HASHED_PASSWORD:?}

networks:
  public:
    external: true
  auth:
    external: true
