version: "3.8"

services:
  wireguard:
    image: weejewel/wg-easy:5
    environment:
      WG_HOST: vpn.${DOMAIN:?}
      WG_DEFAULT_DNS: ${DEFAULT_DNS:-192.168.1.200}
      PASSWORD: ${PASSWORD:?}
      WG_PERSISTENT_KEEPALIVE: 15
    volumes:
      - wireguard_etc_wireguard:/etc/wireguard
    networks:
      - bridge
    ports:
      - target: 51820
        published: 51820
        protocol: udp
        mode: host
      - target: 51821
        published: 51821
        protocol: tcp
        mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    deploy:
      placement:
        constraints:
          - 'node.hostname == manager1' 
          
networks:
  bridge:
   external: true

volumes:
  wireguard_etc_wireguard:
