version: "3.8"

services:
  wireguard:
    image: weejewel/wg-easy:5
    environment:
      WG_HOST: vpn.${DOMAIN:?}
      WG_DEFAULT_DNS: ${DEFAULT_DNS:-192.168.1.200}
      PASSWORD: ${PASSWORD:?}
    volumes:
      - wireguard_etc_wireguard:/etc/wireguard
    networks:
      - host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    deploy:
      placement:
        constraints: [node.hostname == manager]

networks:
  host:
    name: host
    external: true

volumes:
  wireguard_etc_wireguard:
