version: "3.8"
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.6
    volumes:
      - opt_adguardhome_work:/opt/adguardhome/work
      - opt_adguardhome_conf:/opt/adguardhome/conf
    networks:
      - traefik_public
    deploy:
      placement:
        constraints:
          - node.hostname == manager1
      labels:
        traefik.enable: "true"
        traefik.http.routers.adguardhome.service: "adguardhome"
        traefik.http.routers.adguardhome.rule: "Host(`adguard.${DOMAIN:?}`)"
        traefik.http.routers.adguardhome.entrypoints: "websecure"
        traefik.http.routers.adguardhome.tls.certresolver: "letsencrypt"
        traefik.http.services.adguardhome.loadbalancer.server.port: 3000
        traefik.http.routers.adguardhome.middlewares: adguardhome-auth
        traefik.http.middlewares.adguardhome-auth.forwardauth.address: http://cloudflare-auth:8080/auth/${CLOUDFLARE_AUTH_AUD:?}
        ## Plain DNS/TCP
        traefik.tcp.routers.adguardhome-dns-tcp.entrypoints: dns-tcp
        traefik.tcp.routers.adguardhome-dns-tcp.rule: HostSNI(`*`)
        traefik.tcp.routers.adguardhome-dns-tcp.service: adguardhome-dns-tcp
        traefik.tcp.services.adguardhome-dns-tcp.loadbalancer.server.port: 53
        ## Plain DNS/UDP
        traefik.udp.routers.adguardhome-dns-udp.entrypoints: dns-udp
        traefik.udp.routers.adguardhome-dns-udp.service: adguardhome-dns-udp
        traefik.udp.services.adguardhome-dns-udp.loadbalancer.server.port: 53
        
networks:
  traefik_public:
    external: true

volumes:
  opt_adguardhome_work:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:?},nfsvers=4
      device: :/adguardhome_opt_adguardhome_work
  opt_adguardhome_conf:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:?},nfsvers=4
      device: :/adguardhome_opt_adguardhome_conf
