version: '3.8'
services:
  cadvisor:
    image: raylas/cadvisor:0.43.0
    networks:
      - internal
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      mode: global

networks:
  internal:
    external: true
