version: '3.8'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.44.0
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      mode: global

networks:
  internal:
    external: true