version: "3.8"

services:
  devantler-cms:
    image: devantler/devantler-cms:v0.0.9
    networks:
      - public
      - internal
    volumes:
      - devantler-cms:/app/wwwroot
    environment:
      ConnectionStrings__Database: Server=piranha-db;Database=master;User=sa;Password=${DB_PASSWORD:?}
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.devantler-cms.rule: "Host(`${DOMAIN:?}`)"
        traefik.http.routers.devantler-cms.entrypoints: "websecure"
        traefik.http.routers.devantler-cms.tls.certresolver: "letsencrypt"
        traefik.http.routers.devantler-cms.service: "devantler-cms"
        traefik.http.services.devantler-cms.loadbalancer.server.port: 5000
  piranha-db:
    image: mcr.microsoft.com/azure-sql-edge:1.0.5
    user: root
    volumes:
      - piranha-db-mssql:/var/opt/mssql
      - piranha-db-mssql-extensibility:/var/opt/mssql-extensibility
      - piranha-db-mssql-extensibility-data:/var/opt/mssql-extensibility/data
      - piranha-db-mssql-extensibility-log:/var/opt/mssql-extensibility/log
    networks:
      - internal
    environment:
      MSSQL_SA_PASSWORD: ${DB-PASSWORD:?}
      ACCEPT_EULA: 1

volumes:
  devantler-cms:
  piranha-db-mssql:
  piranha-db-mssql-extensibility:
  piranha-db-mssql-extensibility-data:
  piranha-db-mssql-extensibility-log:
  
  
networks:
  public:
    external: true
  internal:
    external: true
