version: "3.8"
services:
  wireguard:
    image: weejewel/wg-easy
    environment:
      WG_HOST: vpn.devantler.com
      PASSWORD: trm!TxZbJU*wT$wC
      WG_POST_UP: iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE

      #WG_DEFAULT_DNS: 8.8.8.8, 8.8.4.4
    volumes:
      - wireguard_etc_wireguard:/etc/wireguard
    networks:
      - public
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    secrets:
      - wireguard_password
      - wireguard_host
    deploy:
      replicas: 1
      labels:
        io.portainerhack.cap_add: NET_ADMIN,SYS_MODULE # Remove when portainer supports capabilities by default
        traefik.enable: "true"
        traefik.http.routers.wireguard.rule: "Host(`vpn.devantler.com`)"
        traefik.http.routers.wireguard.entrypoints: "websecure"
        traefik.http.routers.wireguard.tls.certresolver: "letsencrypt"
        traefik.http.routers.wireguard.service: "wireguard"
        traefik.http.services.wireguard.loadbalancer.server.port: 51821
        traefik.udp.routers.wireguard.entrypoints: "vpn"
        traefik.udp.routers.wireguard.service: "wireguard"
        traefik.udp.services.wireguard.loadbalancer.server.port: 51820

networks:
  public:
    external: true
volumes:
  wireguard_etc_wireguard:
secrets:
  wireguard_password:
    external: true
  wireguard_host:
    external: true
