version: '3.8'

services:
  portainer-capability-manager:
    image: fopina/portainer-capability-manager:0.1.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public

networks:
  public:
    external: true
