version: "3.8"
services:
  wg-easy:
    image: weejewel/wg-easy
    environment:
      - WG_HOST=vpn.devantler.com
      - PASSWORD=Jepfa202042
      #- WG_HOST=/run/secrets/wireguard_host
      #- PASSWORD=/run/secrets/wireguard_password
      # - WG_DEFAULT_DNS=1.1.1.1
    volumes:
      - wireguard_etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    secrets:
      - wireguard_password
    labels:
      io.portainerhack.cap_add: NET_ADMIN,SYS_MODULE
      traefik.enable: "true"
      traefik.http.routers.wg-easy.service: "wg-easy"
      traefik.http.routers.wg-easy.rule: "Host(`vpn.devanter.com`)"
      traefik.http.services.wg-easy.loadbalancer.server.port: 51821
    deploy:
      mode: replicated
      replicas: 1
volumes:
  wireguard_etc_wireguard:
secrets:
  wireguard_password:
    external: true
  wireguard_host:
    external: true
