version: '3.8'

services:
  keepalived:
    image: osixia/keepalived:release-2.1.5-dev
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    networks:
      - host
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    environment:
      KEEPALIVED_VIRTUAL_IPS: "192.168.1.200"
    
networks:
  host:
    external: true
    name: host