version: '3.8'

services:
  keepalived:
    image: osixia/keepalived:2.0.20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
    networks:
      - host
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    environment:
      KEEPALIVED_VIRTUAL_IPS: "192.168.1.200"

networks:
  host:
    external: true
    name: host