version: "3.8"

services:
  keepalived:
    image: lettore/keepalived:arm64v8-latest
    networks:
      - host
    cap_add:
      - NET_ADMIN
    environment:
      KEEPALIVED_VIRTUAL_IPS: "${VIRTUAL_IPS:-192.168.1.200}"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
        prometheus-job: keepalived
networks:
  host:
    external: true
    name: host
