version: '3.8'

services:
  keepalived:
    image: geoffh1977/keepalived:2.0.19
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    environment:
      VIRTUAL_IP: "192.168.1.200"