version: '3.8'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/cloudflare_api_token
    secrets:
      - mariadb_root_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

secrets:
  mariadb_root_password:
    external: true