version: "3.8"

services:
  nfs-server:
    image: gists/nfs-server:2.5.4
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    volumes:
      - ${NFS_SHARE_PATH}:/nfs-share
    deploy:
      labels:
        io.portainerhack.cap_add: SYS_ADMIN,SETPCAP
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager1