version: "3.8"
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:2.9.14'
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
      - '81:81'
    volumes:
      - nginx_data:/data
      - nginx_etc_letsencryptx:/etc/letsencryptx
volumes:
  nginx_data:
  nginx_etc_letsencryptx: