version: "3.8"
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:2.9.14'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
      - '22:22'
    volumes:
      - nginx_proxy_manager_data:/data
      - nginx_proxy_manager_etc_letsencryptx:/etc/letsencryptx
volumes:
  nginx_proxy_manager_data:
  nginx_proxy_manager_etc_letsencryptx:
