version: "3.8"
services:
  nginx:
    image: 'jc21/nginx-proxy-manager:2.9.14'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data/nginx/data:/data
      - ./data/nginx/etc-letsencrypt:/etc/letsencrypt