version: "3.8"

services:
  picoshare:
    image: mtlynch/picoshare:1.0.7
    networks:
      - traefik-public
    environment:
      PORT: 3001
      PS_SHARED_SECRET: "${PASSWORD:?}"
    volumes:
      - data:/data
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.picoshare.rule: "Host(`picoshare.${DOMAIN:?}`)"
        traefik.http.routers.picoshare.entrypoints: "websecure"
        traefik.http.routers.picoshare.tls.certresolver: "letsencrypt"
        traefik.http.services.picoshare.loadbalancer.server.port: 3001
        traefik.http.routers.picoshare.service: "picoshare"

networks:
  traefik-public:
    external: true

volumes:
  data:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:?},nfsvers=4
      device: :/picoshare_data
