version: "3.8"
services:
  pihole:
    hostname: pihole.${DOMAIN:?}
    image: pihole/pihole:2022.01.1
    environment:
      TZ: 'Europe/Copenhagen'
      PIHOLE_DNS_: 1.1.1.1
      ServerIP: 192.168.1.201
      DNSMASQ_LISTENING: all
      WEBPASSWORD: ""
    volumes:
      - pihole_etc_pihole:/etc/pihole
      - pihole_etc_dnsmasq.d:/etc/dnsmasq.d
    networks:
      - traefik
    deploy:
      placement:
        constraints: 
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.http.routers.pihole.rule: "Host(`pihole.${DOMAIN:?}`)"
        traefik.http.routers.pihole.entrypoints: "websecure"
        traefik.http.routers.pihole.tls.certresolver: "letsencrypt"
        traefik.http.services.pihole.loadbalancer.server.port: 80
        traefik.http.routers.pihole.middlewares: pihole-add-prefix@docker, pihole-auth@docker
        traefik.http.middlewares.pihole-add-prefix.addprefix.prefix: /admin
        traefik.http.middlewares.pihole-auth.forwardauth.address: http://cloudflare-auth:8080/auth/${CLOUDFLARE_AUTH_AUD:?}
        traefik.http.routers.pihole.service: "pihole"
        # 53/tcp
        traefik.tcp.routers.pihole-tcp.rule: HostSNI(`*`)
        traefik.tcp.routers.pihole-tcp.service: pihole-tcp
        traefik.tcp.routers.pihole-tcp.entrypoints: pihole-tcp
        traefik.tcp.services.pihole-tcp.loadbalancer.server.port: 53
        # 53/udp
        traefik.udp.routers.pihole-udp.entrypoints: pihole-udp
        traefik.udp.routers.pihole-udp.service: pihole-udp
        traefik.udp.services.pihole-udp.loadbalancer.server.port: 53

networks:
  traefik:
    external: true

volumes:
  pihole_etc_pihole:
  pihole_etc_dnsmasq.d:
