version: "3.8"
services:
  pihole:
    image: pihole/pihole:2022.04.2
    hostname: pihole.devantler.com
    environment:
      VIRTUAL_HOST: pihole.${DOMAIN:?}
      TZ: "Europe/Copenhagen"
      PIHOLE_DNS_: 1.1.1.1
      # DNSMASQ_LISTENING: all
      WEBPASSWORD: ""
    volumes:
      - pihole:/etc/pihole
      - pihole:/etc/dnsmasq.d
    networks:
      - public
    deploy:
      placement:
        constraints:
          - node.hostname == manager1
      labels:
        traefik.enable: "true"
        traefik.http.routers.pihole.service: "pihole"
        traefik.http.routers.pihole.rule: "Host(`pihole.${DOMAIN:?}`)"
        traefik.http.routers.pihole.entrypoints: "websecure"
        traefik.http.routers.pihole.tls.certresolver: "letsencrypt"
        traefik.http.routers.pihole.middlewares: pihole-admin-prefix@docker, pihole-auth@docker
        traefik.http.middlewares.pihole-admin-prefix.addprefix.prefix: /admin
        traefik.http.middlewares.pihole-auth.forwardauth.address: http://cloudflare-auth:8080/auth/${CLOUDFLARE_AUTH_AUD:?}
        traefik.http.services.pihole.loadbalancer.server.port: 80
        
        ## TCP Routers/Service
        traefik.tcp.routers.pihole-tcp.entrypoints: dns-tcp
        traefik.tcp.routers.pihole-tcp.rule: HostSNI(`*`)
        traefik.tcp.routers.pihole-tcp.service: pihole-tcp
        traefik.tcp.services.pihole-tcp.loadbalancer.server.port: 53

         ## UDP Routers/Services
        traefik.udp.routers.pihole-udp.entrypoints: dns-udp
        traefik.udp.routers.pihole-udp.service: pihole-udp
        traefik.udp.services.pihole-udp.loadbalancer.server.port: 53

networks:
  public:
    external: true

volumes:
  pihole:
