version: '3.8'

services:
  portainer:
    image: portainer/portainer-ee:2.12.2
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - public
      - agent_network
    deploy:
      placement:
        constraints: [ node.role == manager ]
      labels:
        traefik.enable: "true"
        # Regular
        traefik.http.routers.portainer.rule: "Host(`portainer.${DOMAIN:?}`)"
        traefik.http.routers.portainer.entrypoints: "websecure"
        traefik.http.routers.portainer.tls.certresolver: "letsencrypt"
        traefik.http.services.portainer.loadbalancer.server.port: 9000
        traefik.http.routers.portainer.service: "portainer"
        # Edge
        traefik.http.routers.edge.rule: "Host(`edge.${DOMAIN:?}`)"
        traefik.http.routers.edge.entrypoints: "websecure"
        traefik.http.routers.edge.tls.certresolver: "letsencrypt"
        traefik.http.services.edge.loadbalancer.server.port: 8000
        traefik.http.routers.edge.service: edge

  agent:
    image: portainer/agent:2.12.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    deploy:
      mode: global

networks:
  public:
    external: true
  agent_network:
    external: true

volumes:
  portainer_data:
