version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - prometheus:/prometheus
      - etc_prometheus:/etc/prometheus
    ports:
      - 9090:9090
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    networks:
      - internal

volumes:
  prometheus:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:?},nfsvers=4
      device: :/prometheus_prometheus
  etc_prometheus:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:?},nfsvers=4
      device: :/prometheus_etc_prometheus

configs:
  prometheus-config:
    external: true

networks:
  internal:
    external: true
    
