version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - prometheus:/prometheus
      - etc_prometheus:/etc/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9090:9090
    networks:
      - monitoring

volumes:
  prometheus:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:?},nfsvers=4
      device: :/prometheus_prometheus
  etc_prometheus:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:?},nfsvers=4
      device: :/prometheus_etc_prometheus

networks:
  monitoring:
    external: true
    
