version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - prometheus:/prometheus
      - etc_prometheus:/etc/prometheus
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    networks:
      - internal

volumes:
  prometheus:
  etc_prometheus:
configs:
  prometheus-config:
    external: true

networks:
  internal:
    external: true
    
