version: "3.8"

services:
  traefik:
    image: traefik:v2.6
    command:
      # Docker swarm configuration
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      # Configure entrypoint
      - --entrypoints.web.address=:80
      - --entrypoints.pihole-tcp.address=:53/tcp
      - --entrypoints.pihole-udp.address=:53/udp
      - --entrypoints.websecure.address=:443
      # SSL configuration
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL:?}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Redirect to HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    environment:
      # CloudFlare specific letsencrypt environment variables (see https://doc.traefik.io/traefik/v2.6/https/acme/#providers)
      CF_API_EMAIL: ${EMAIL:?}
      CF_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN:?}
    ports:
      - 80:80
      - 53:53/tcp
      - 53:53/udp
      - 443:443
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  traefik:
    external: true

volumes:
  letsencrypt: null
