version: "3.8"

services:
  traefik:
    image: traefik:v2.7
    command:
      # Docker swarm configuration
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=public
      # Configure entrypoint
      - --entrypoints.dns-tcp.address=:53/tcp
      - --entrypoints.dns-udp.address=:53/udp
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # SSL configuration
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL:?}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Redirect to HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    environment:
      # CloudFlare specific letsencrypt environment variables (see https://doc.traefik.io/traefik/v2.6/https/acme/#providers)
      CF_API_EMAIL: ${EMAIL:?}
      CF_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN:?}
    ports:
      - 53:53/tcp # dns
      - 53:53/udp # dns
      - 80:80 # http
      - 443:443 # https
    networks:
      - traefik_public
      - traefik_auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  traefik_public:
    external: true
  traefik_auth:
    external: true

volumes:
  letsencrypt:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:?},nfsvers=4
      device: :/traefik_letsencrypt
