version: "3.8"
services:
  wg-easy:
    image: weejewel/wg-easy
    environment:
      - WG_HOST=vpn.devantler.com
      - PASSWORD=/run/secrets/wireguard_password
      # - WG_DEFAULT_DNS=1.1.1.1
    volumes:
      - wireguard_etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - CAP_NET_ADMIN
      - CAP_SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    secrets:
      - wireguard_password
volumes:
  wireguard_etc_wireguard:
secrets:
  wireguard_password:
    external: true