version: "3.8"

services:
  wireguard:
    image: weejewel/wg-easy:5
    environment:
      WG_HOST: vpn.${DOMAIN:?}
      WG_DEFAULT_DNS: ${DEFAULT_DNS:-192.168.1.200}
      PASSWORD: ${PASSWORD:?}
    volumes:
      - wireguard_etc_wireguard:/etc/wireguard
    networks:
      - host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    deploy:
      labels:
        io.portainerhack.cap_add: NET_ADMIN,SYS_MODULE

networks:
  host:
    name: host
    external: true

volumes:
  wireguard_etc_wireguard:
