version: "3.8"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:1.0.20210914
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - SERVERURL=vpn.devantler.com
      - SERVERPORT=51820
      - PEERS=macbook
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - wireguard_config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
volumes:
  wireguard_config: