version: "3.8"
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    environment:
      - PUID=1000
      - PGID=1000
    configs:
      - source: cloudflare_ddns_config
        target: /config.json
        uid: 1000
        gid: 1000

configs:
  cloudflare_ddns_config:
    external: true