version: "3.8"

services:
  nfs-server:
    image: gists/nfs-server:2.5.4
    ports:
      - 2049:2049
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    volumes:
      - nfs-share:/nfs-share
    deploy:
      labels:
        io.portainerhack.cap_add: SYS_ADMIN,SETPCAP
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager1

volumes:
  nfs-share: