version: "3.8"

services:
  nfs-server:
    image: gists/nfs-server:2.5.4
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    volumes:
      - nfs-share:/nfs-share
    networks:
      - storage
    deploy:
      labels:
        io.portainerhack.cap_add: SYS_ADMIN,SETPCAP
      placement:
        constraints:
          - node.role == manager
          - node.hostname == manager1

volumes:
  nfs-share:

networks:
  storage:
    external: true