version: "3.8"
services:
  cloudflare-ddns:
    image: joshava/cloudflare-ddns
    configs:
      - source: cloudflare-ddns-config
        target: /app/config.yaml

configs:
  cloudflare-ddns-config:
    external: true