version: '3.8'
services:
  node-exporter:
    image: prom/node-exporter:v1.3.1
    command:
      - '--path.rootfs=/host'
    command:
    networks:
      - host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
      
networks:
  host:
    external: true
