version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.33.0
    volumes:
      - prometheus:/prometheus
      - etc_prometheus:/etc/prometheus
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - traefik
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.prometheus.rule: "Host(`prometheus.${DOMAIN:?}`)"
        traefik.http.routers.prometheus.entrypoints: "websecure"
        traefik.http.routers.prometheus.tls.certresolver: "letsencrypt"
        traefik.http.services.prometheus.loadbalancer.server.port: 8080
        traefik.http.routers.prometheus.service: "prometheus"
        traefik.http.routers.prometheus.middlewares: prometheus-auth
        traefik.http.middlewares.prometheus-auth.basicauth.users: ${ADMIN_USER:?}:${HASHED_PASSWORD:?}

volumes:
  prometheus:
  etc_prometheus:
configs:
  prometheus-config:
    external: true

networks:
  traefik:
    external: true
